<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StoreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stores')->insert([
            [
                'category_id' => 1,
                'store_name' => '焼き魚のさかな屋',
                'image' => 'images/1.png',
                'store_description' => '四季折々の食材を使った本格和食を提供する落ち着いた空間',
                'address' => '東京都港区南青山1-1-1',
                'postal_code' => '107-0062',
                'tel' => '03-1111-1111',
                'business_hours' => '11:30〜22:00',
                'holiday' => '月曜',
                'price' => 3500,
            ],
            [
                'category_id' => 1,
                'store_name' => '旬彩和膳 たけのこ',
                'image' => 'images/2.png',
                'store_description' => '四季折々の食材を使った本格和食を提供する落ち着いた空間',
                'address' => '東京都港区南青山1-1-1',
                'postal_code' => '107-0062',
                'tel' => '03-1111-1111',
                'business_hours' => '11:30〜22:00',
                'holiday' => '月曜',
                'price' => 3500,
            ],
            [
                'category_id' => 2,
                'store_name' => 'グリル・ド・パリ',
                'image' => 'images/3.png',
                'store_description' => '本場のステーキとワインが楽しめるヨーロピアンスタイルの洋食店',
                'address' => '東京都渋谷区恵比寿2-2-2',
                'postal_code' => '150-0013',
                'tel' => '03-2222-2222',
                'business_hours' => '12:00〜23:00',
                'holiday' => '火曜',
                'price' => 4000,
            ],
            [
                'category_id' => 3,
                'store_name' => '中華楼 龍鳳',
                'image' => 'images/4.png',
                'store_description' => '四川・広東・北京料理を揃えた本格中華レストラン',
                'address' => '東京都新宿区歌舞伎町3-3-3',
                'postal_code' => '160-0021',
                'tel' => '03-3333-3333',
                'business_hours' => '11:00〜22:30',
                'holiday' => '水曜',
                'price' => 3000,
            ],
            [
                'category_id' => 4,
                'store_name' => '韓味屋 ソウル',
                'image' => 'images/5.png',
                'store_description' => '韓国の家庭料理と焼肉が楽しめるアットホームな店',
                'address' => '東京都豊島区池袋4-4-4',
                'postal_code' => '171-0022',
                'tel' => '03-4444-4444',
                'business_hours' => '12:00〜22:00',
                'holiday' => '木曜',
                'price' => 2800,
            ],
            [
                'category_id' => 5,
                'store_name' => 'トラットリア・ミラノ',
                'image' => 'images/6.png',
                'store_description' => '薪窯ピザと手打ちパスタが自慢のイタリアンレストラン',
                'address' => '東京都世田谷区三軒茶屋5-5-5',
                'postal_code' => '154-0004',
                'tel' => '03-5555-5555',
                'business_hours' => '11:30〜22:30',
                'holiday' => '火曜',
                'price' => 3200,
            ],
            [
                'category_id' => 6,
                'store_name' => 'ビストロ・ル・ブルゴーニュ',
                'image' => 'images/7.png',
                'store_description' => 'フランス郷土料理と自然派ワインが楽しめる隠れ家ビストロ',
                'address' => '東京都文京区本郷6-6-6',
                'postal_code' => '113-0033',
                'tel' => '03-6666-6666',
                'business_hours' => '17:00〜23:00',
                'holiday' => '月曜',
                'price' => 4500,
            ],
            [
                'category_id' => 7,
                'store_name' => 'スパイスロード',
                'image' => 'images/8.png',
                'store_description' => '本格インドカレーとタンドール料理が味わえるスパイシーな空間',
                'address' => '東京都墨田区錦糸町7-7-7',
                'postal_code' => '130-0013',
                'tel' => '03-7777-7777',
                'business_hours' => '11:00〜21:30',
                'holiday' => '水曜',
                'price' => 2500,
            ],
            [
                'category_id' => 8,
                'store_name' => 'タイ屋台 チャオ',
                'image' => 'images/9.png',
                'store_description' => 'バンコクの屋台を再現した本格タイ料理店',
                'address' => '東京都江東区亀戸8-8-8',
                'postal_code' => '136-0071',
                'tel' => '03-8888-8888',
                'business_hours' => '12:00〜22:00',
                'holiday' => '木曜',
                'price' => 2700,
            ],
            [
                'category_id' => 9,
                'store_name' => 'ベトナム食堂 フォーハノイ',
                'image' => 'images/10.png',
                'store_description' => 'フォーやバインミーなどベトナムの定番料理が揃う人気店',
                'address' => '東京都大田区蒲田9-9-9',
                'postal_code' => '144-0052',
                'tel' => '03-9999-9999',
                'business_hours' => '11:30〜21:00',
                'holiday' => '火曜',
                'price' => 2600,
            ],
            [
                'category_id' => 10,
                'store_name' => 'バル・エスパーニャ',
                'image' => 'images/11.png',
                'store_description' => 'タパスとパエリアが楽しめるスペインバル',
                'address' => '東京都中央区銀座10-10-10',
                'postal_code' => '104-0061',
                'tel' => '03-1010-1010',
                'business_hours' => '17:00〜23:00',
                'holiday' => '月曜',
                'price' => 3800,
            ],
            [
                'category_id' => 11,
                'store_name' => 'メキシカン・グリル タコスラボ',
                'image' => 'images/12.png',
                'store_description' => 'タコス・ブリトー・ナチョスが揃う陽気なメキシコ料理店',
                'address' => '東京都杉並区高円寺11-11-11',
                'postal_code' => '166-0002',
                'tel' => '03-1111-1112',
                'business_hours' => '12:00〜22:00',
                'holiday' => '水曜',
                'price' => 2900,
            ],
            [
                'category_id' => 12,
                'store_name' => 'ラーメン道場 一心',
                'image' => 'images/13.png',
                'store_description' => '濃厚豚骨からあっさり醤油まで揃うラーメン専門店',
                'address' => '東京都北区赤羽12-12-12',
                'postal_code' => '115-0045',
                'tel' => '03-1212-1212',
                'business_hours' => '11:00〜翌1:00',
                'holiday' => 'なし',
                'price' => 1000,
            ],
            [
                'category_id' => 13,
                'store_name' => 'そば処 まつや',
                'image' => 'images/14.png',
                'store_description' => '石臼挽きの手打ちそばと讃岐うどんが味わえる老舗',
                'address' => '東京都台東区浅草13-13-13',
                'postal_code' => '111-0032',
                'tel' => '03-1313-1313',
                'business_hours' => '11:00〜20:00',
                'holiday' => '火曜',
                'price' => 1200,
            ],
            [
                'category_id' => 14,
                'store_name' => '焼肉 炎舞',
                'image' => 'images/15.png',
                'store_description' => '黒毛和牛を炭火で焼き上げる高級焼肉店',
                'address' => '東京都品川区五反田14-14-14',
                'postal_code' => '141-0031',
                'tel' => '03-1414-1414',
                'business_hours' => '17:00〜23:00',
                'holiday' => '水曜',
                'price' => 5000,
            ],
            [
                'category_id' => 15,
                'store_name' => '寿司割烹 海音',
                'image' =>'images/16.png',
                'store_description' => '職人が握る旬の寿司と季節の一品料理が楽しめる本格店',
                'address' => '東京都港区六本木15-15-15',
                'postal_code' => '106-0032',
                'tel' => '03-1515-1515',
                'business_hours' => '12:00〜22:00',
                'holiday' => '月曜',
                'price' => 6000,
            ],
            [
                'category_id' => 16,
                'store_name' => 'カレー工房 スパイスマジック',
                'image' => 'images/17.png',
                'store_description' => 'スパイスにこだわった創作系カレー専門店',
                'address' => '東京都中野区中野16-16-16',
                'postal_code' => '164-0001',
                'tel' => '03-1616-1616',
                'business_hours' => '11:30〜21:00',
                'holiday' => '火曜',
                'price' => 1800,
            ],
            [
                'category_id' => 17,
                'store_name' => '居酒屋 ほろ酔い横丁',
                'image' => 'images/18.png',
                'store_description' => '串焼き・刺身・地酒が揃う昭和レトロな居酒屋',
                'address' => '東京都練馬区大泉学園17-17-17',
                'postal_code' => '178-0063',
                'tel' => '03-1717-1717',
                'business_hours' => '17:00〜24:00',
                'holiday' => '日曜',
                'price' => 2800,
            ],
            [
                'category_id' => 18,
                'store_name' => 'カフェ・ド・ルミエール',
                'image' => 'images/19.png',
                'store_description' => '自家焙煎コーヒーと手作りスイーツが人気の癒し系カフェ',
                'address' => '東京都目黒区自由が丘18-18-18',
                'postal_code' => '152-0035',
                'tel' => '03-1818-1818',
                'business_hours' => '10:00〜19:00',
                'holiday' => '水曜',
                'price' => 1500,
            ],
            [
                'category_id' => 19,
                'store_name' => 'ビュッフェガーデン 彩菜',
                'image' => 'images/20.png',
                'store_description' => '和洋中の料理が揃うホテルライクなビュッフェレストラン',
                'address' => '東京都江戸川区西葛西19-19-19',
                'postal_code' => '134-0088',
                'tel' => '03-1919-1919',
                'business_hours' => '11:00〜21:00',
                'holiday' => '月曜',
                'price' => 3500,
            ],
            [
                'category_id' => 20,
                'store_name' => '海鮮処 魚心',
                'image' => 'images/21.png',
                'store_description' => '築地直送の鮮魚を使った海鮮丼と刺身が自慢の店',
                'address' => '東京都中央区築地20-20-20',
                'postal_code' => '104-0045',
                'tel' => '03-2020-2020',
                'business_hours' => '11:00〜22:00',
                'holiday' => '火曜',
                'price' => 3200,
            ],
            [
                'category_id' => 21,
                'store_name' => '焼き鳥本舗 とり吉',
                'image' => 'images/22.png',
                'store_description' => '備長炭で焼き上げる本格焼き鳥と地酒が楽しめる専門店',
                'address' => '東京都新宿区西新宿21-21-21',
                'postal_code' => '160-0023',
                'tel' => '03-2121-2121',
                'business_hours' => '17:00〜23:30',
                'holiday' => '月曜',
                'price' => 2800,
            ],

        ]);
    }
}
